# See https://wiki.hyprland.org/Configuring/Monitors/
# List current monitors and resolutions possible: hyprctl monitors
# Format: monitor = [port], resolution, position, scale


monitor = DP-2, 2560x1440@180, auto, auto
monitor = DP-1, 2560x1440@180, auto, auto