onboarding = false

[keys]
prefix = "ctrl+space"

[theme]
name = "dracula"
auto_switch = false

[ui]
prompt_new_tab_name = false
agent_panel_sort = "spaces"
show_agent_labels_on_pane_borders = true

[ui.sound]
enabled = true

[ui.toast]
delivery = "terminal"
